### ISSUE TITLE
GPC Support Representation - versioning

### ISSUE THREAD

**Issue by mnot** [globalprivacycontrol/gpc-spec#20]
The JSON format specifies a `version` field, but not how it's used, beyond:

> The value of the version member MUST be the number 1.

A recipient might read that if the version isn't `1`, the format isn't valid, and ignore it -- is that the intent here?

If not, changes would be backwards-compatible, which means a version field isn't necessary, and incompatible changes could be introduced by changing the well-known resource name.

**Comment by darobin** [comment]
@SebastianZimmeck Thanks for assigning this to me, but I've been saying that `version` serves no purpose and should be removed since the beginning! See also https://berjon.com/xmlbp-naive-versioning/.

**Comment by SebastianZimmeck** [comment]
> but I've been saying that version serves no purpose and should be removed since the beginning!

As long as there is backward compatibility in case GPC is extended, I am personally fine with whatever mechanism can accomplish that. Though, if there is a best practice, we should follow that practice as it will make it easier for implementers.

**Comment by pes10k** [comment]
I am 100% a-okay to remove the field too.  I suggested it originally out of some "always stick a version number on it" advice I picked up… somewhere. But I'm convinced by @darobin that thats more cargo-cult-ish than materially useful. I'm 👍 on removing it too

**Comment by darobin** [comment]
We resolved this by removing `version` and adding `lastUpdate`. It's in the latest version.
