### ISSUE TITLE
Use RFC3339 for lastUpdate field of support resource

### ISSUE THREAD

**Issue by braedon** [globalprivacycontrol/gpc-spec#21]
Is it possible to change the `lastUpdate` field of `/.well-known/gpc.json` to RFC3339, rather than ISO8601?

The [ISO8601 spec](https://www.iso.org/iso-8601-date-and-time-format.html) is behind a pay wall, which makes it difficult for implementers (particularly parsers) to know what possible values the `lastUpdate` field can take.

[RFC3339](https://datatracker.ietf.org/doc/html/rfc3339) is a "profile" of ISO8601, so essentially describes the same thing, but is freely available, simpler/more specific, and is specifically intended as the "date and time format for use in Internet protocols".

**Comment by SebastianZimmeck** [comment]
Thanks, @braedon! That seems even better. @darobin, what do you think?

**Comment by seanturner** [comment]
Please also add "be" to the following sentence:

     MUST an ISO 8601 date

Also, need a reference for either RFC 3339 or ISO 8601.

**Comment by SebastianZimmeck** [comment]
Thanks, @braedon and @seanturner. I changed the spec to RFC3339 and fixed the typo.
