### ISSUE TITLE
Please consider bringing this spec to Web Privacy CG

### ISSUE THREAD

**Issue by othermaciej** [globalprivacycontrol/gpc-spec#23]
The Web Privacy Community Group aims to incubate privacy specifications for eventual standards track placement. GPC is implemented by numerous extensions and at least one browser (Brave) so it would fit.

**Comment by SebastianZimmeck** [comment]
Thanks for the suggestion, @othermaciej! We are discussing GPC in Privacy Community Group [here](https://github.com/privacycg/proposals/issues/10). Feel free to chime in ...

**Comment by SebastianZimmeck** [comment]
If you want to discuss further here, @othermaciej, feel free to reopen this issue.
