### ISSUE TITLE
Follow up question...

### ISSUE THREAD

**Issue by HeinzBaumann** [globalprivacycontrol/gpc-spec#25]
Just curious given the spec is still listed as a draft, where is this proposal in regards to making it a standard at w3c? I see that Firefox is starting to implement it. Do you have commitment from other browser developers too?

**Comment by darobin** [comment]
The way W3C standards work is that [adoption precedes standardisation](https://www.w3.org/2021/Process-20211102/#implementation-experience), and we're seeing strong adoption.

This is an issue tracker for technical discussion about the GPC standard, please don't use it for general questions and without using a descriptive subject. The [official site](https://globalprivacycontrol.org/) has an FAQ and contact details for the project.
