### ISSUE TITLE
Setting and reading headers

### ISSUE THREAD

**Issue by martymcflyDMC** [globalprivacycontrol/gpc-spec#28]
I have been doing some testing using a simple NGINX server and testing on Brave and Chrome browsers. 

When I set `Sec-GPC = 0` on a page these are the following results:

* Brave `navigator.globalPrivacyControl` is always true
* Chrome  `navigator.globalPrivacyControl` is undefined

Shouldn't the client-side be reading the value of the header?

**Comment by SebastianZimmeck** [comment]
> Shouldn't the client-side be reading the value of the header?

Independently of whether you set GPC via a header or JavaScript property, the GPC signal would need to be sent from the client to the server. For example, for every web request that you send via Brave, you should see the GPC header attached to it. You can use [OptMeowt](https://chrome.google.com/webstore/detail/optmeowt/hdbnkdbhglahihjdbodmfefogcjbpgbo) to turn GPC on and off for individual domains. We provide [client- and server-side sample implementations for setting GPC](https://global-privacy-control.glitch.me/).

**Comment by SebastianZimmeck** [comment]
@martymcflyDMC, please feel free to reopen if you think this needs further discussion.
