### ISSUE TITLE
Latest published version link returns 404

### ISSUE THREAD

**Issue by coolharsh55** [globalprivacycontrol/gpc-spec#31]
Hi. The latest published version link in the specs at https://globalprivacycontrol.github.io/gpc-spec/ is https://www.w3.org/gpc/ which returns a 404.

If this is NOT an error on the W3 side, and that url has not been registered/provided by w3.org, then an alternative (if needed) for 'purl' is to use [w3id](https://github.com/perma-id/w3id.org) e.g. to get https://w3id.org/gpc

**Comment by SebastianZimmeck** [comment]
Thanks for pointing out this issue, @coolharsh55! It is resolved now.
