### ISSUE TITLE
lack of version

### ISSUE THREAD

**Issue by patmmccann** [globalprivacycontrol/gpc-spec#40]
Does it make sense to append a version to signals to future proof the spec for iteration?

**Comment by mnot** [comment]
Versioning inside of HTTP headers is a bit of an anti-pattern. It's better to just mint a new header field if you need to make backwards-incompatible changes.

**Comment by SebastianZimmeck** [comment]
The [GPC support resource](https://globalprivacycontrol.github.io/gpc-spec/#gpc-support-representation) has a date and time that is intended for future-proofing and also give implementers flexibility:

> This indicates the time at which the statement of support was made, such that later changes to the meaning of the GPC standard should not affect the interpretation of the resource for legal purposes.

**Comment by SebastianZimmeck** [comment]
I am closing this issue as resolved. If there is more need for discussion, feel free to reopen.

**Comment by patmmccann** [comment]
the browser header is not the only place the gpc is communicated; the IAB Techlab has incorporated it into server to server open rtb headers.
