### ISSUE TITLE
Explain relationship to DNT

### ISSUE THREAD

**Issue by darobin** [globalprivacycontrol/gpc-spec#5]
Filed on behalf of @anssiko: It might be worthwhile to explain upfront the relationship with DNT given the shared broader problem space and similar API shape that might confuse some.

**Comment by michael-oneill** [comment]
The TPWG TPE should at least be mentioned in the References: https://www.w3.org/TR/tracking-dnt/

**Comment by michael-oneill** [comment]
Created new issue for that

**Comment by asoltani** [comment]
Resolvedby https://github.com/globalprivacycontrol/gpc-spec/pull/16
