### ISSUE TITLE
Host the GPC Support Resource at /.well-known/gpc.json

### ISSUE THREAD

**Issue by dmarti** [globalprivacycontrol/gpc-spec#9]
Add `.json` to the end of the "well-known" URL, to facilitate implementation by sites with legacy web servers or shared hosting.

(This is what the IAB Tech Lab does with `ads.txt` and `sellers.json`)

It's easy to configure `IndexDocument` and MIME types if you have access to the web server config files but this is not always possible for the person responsible for adding 3rd-party JavaScript to a site.

**Comment by dharb** [comment]
Fully in support of this change, thanks @dmarti. Needing to serve an extensionless file from a static site without server access (Github pages for example) overcomplicates things unnecessarily.

**Comment by dharb** [comment]
I'll update our sites (reference server and landing page) and documentation to reflect the change.
